config/routes.rb
Rails.application.routes.draw do
  #resources :lists, only: [:new, :create]
  resources :users do
    resources :lists do
      resources :list_items, only: [:new, :edit, :update]
    end
  end
  #resources :items
  resources :list_items, except: [:index, :new]
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:index, :show] do
    resources :items, only: [:index, :new, :create, :show]
  end
  get '/' => 'sessions#home'
  get '/signup' => 'users#new'
	get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  get '/auth/facebook/callback' =>'sessions#facebook_omni'
  post '/lists/:id' => 'lists#destroy'
  get '/logout' => 'sessions#destroy'
 # post '/list/remove' => 'list#destroy'
  #post '/categories/:id/items/new' => 'items#create'
  #post '/categories/:id/items/new' => 'list_items#create'
  # get '/categories' => 'categories#index'
  # get '/categories/:id/items/:item_id' =>  'items#index'
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
    has_many :list_items, dependent: :destroy
    has_many :items, through: :list_items

    validates :name, presence: true
    #validates :name, uniqueness: true
# Make ssure that a list is unique only to the current user
validates :name, uniqueness: { scope: :user_id, message: "You already have a list that is named this." }

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
   # include ActionView::Helpers::ListItemsHelper::find_listItem
   include ListsHelper

   def index
        @lists = List.all
    
   end

   def new
    @list = List.new
   end

   def create
    @user = User.find_by(id: session[:user_id])
    @list = @user.lists.build(list_params)
 
    if @list.save
        redirect_to user_list_path(@user, @list)
    else
        render :new
    end
   end

   def show
    @list = List.find(params[:id])
   
    @user = User.find(@list.user_id)
    @list_item = ListItem.where(list_id: @list.id)
  #  @listItem = ListItem.find_by(list_id: params[:id], item_id: item.id)
  # binding.pry

   end

   def destroy
       # binding.pry
    ListItem.find_list(params[:id]).destroy_all #Look for all instances of the list in the list item table
    #ListItem.where(list_id: params[:id]).destroy_all  
    list = List.find_by(id: params[:id])
    list.destroy
    flash[:destroy] = "#{list.name} is now removed"
    redirect_to user_path(current_user)

   end


private

    def list_params
        params.require(:list).permit(:name)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
    def findUser(list)
        User.find_by(id: list.user_id)     
    end

    def display_other_lists_only(list)
        if current_user.id != list.user_id
            link_to list.name.capitalize, user_path(list.user_id)   
        end
    end

    def display_other_username_only(list)
        if current_user.id != (list.user_id)
            findUser(list).username
        end
    end

end

app/views/lists/index.html.erb
<div class="col-md-12">
    <h1>All Gift Lists</h1>
    <h4>Browse other people gift lists</h4>
    <div class="row list">
        <ul class="list-group list-group-flush">
            <% @lists.each do |list| %>
               <% if current_user.id != list.user_id %>
                    <li class="list-group-item"><%= link_to list.name.capitalize, user_path(list.user_id)  %> | <%= findUser(list).username %></li>
                <% end %>
            <% end %>
        </ul>
    </div>
    <div><%= link_to "Go back to your own gift lists", user_path(current_user), class: "btn btn-primary btn-block" %></div>
</div>

app/views/lists/new.html.erb
<div class="col-md-12">
    <h1>Create a new list</h1>

    <%= form_for(@list, url: user_lists_path) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.submit "Create New List"%>
    <% end %>
</div>

app/views/lists/show.html.erb
<div class="col-md-12">
    <h1><%= @user.username.capitalize %>'s, <%= @list.name.capitalize %> Gift List</h1>
    
	<% if !flash[:destroy].blank? %>
		<div class="alert alert-info">
			<%= flash[:destroy] %>
		</div>
	<% end %>

    <div class="row list">
        <ul class="list-group list-group-flush">
            <% @list.items.each do |item| %>
                <li class="list-group-item">
                
                    <% if current_user != @user %>
                        <%= form_for([@list, item]) do |f| %>
                            <%= f.check_box :checked, :class => "toggle", :checked => ( true if found_listItem(item, @list).purchased? ) %> 
                        <% end %>
                    <% end %>

                    <% if @user.id == current_user.id && found_listItem(item, @list).purchased? %>
                        *** Purchased by: <%= User.find(found_listItem(item, @list).user_id).username.capitalize %> *** | 
                    <% end %>

                    <%= item.name %> 
                
                    <% if @user.id == current_user.id %>
                    | <%= link_to "Remove Item", find_listItem(item), method: :delete, data: { confirm: "Are you sure you want to remove this item?" } %>
                    <% end %>
                    
                </li>
                    
            <% end %>
        </ul>
    </div>
    <div class="row">
    <% if @user.id == current_user.id %>
        <%= link_to "Add Items To Your List",  categories_path, class: "btn btn-primary" %>  <%= link_to "Go to all of your lists", user_path(@user), class: "btn btn-secondary" %>
    <% else %>
        <%= link_to "Go back to your own gift lists", user_path(current_user), class: "btn btn-primary" %>  <%= link_to "See other's gift lists!", lists_path, class: "btn btn-secondary" %>
    <% end %>
    </div>
</div>

 