config/routes.rb
Rails.application.routes.draw do
  #resources :lists, only: [:new, :create]
  resources :users do
    resources :lists do
      resources :list_items, only: [:new, :edit, :update]
    end
  end
  #resources :items
  resources :list_items, except: [:index, :new]
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:index, :show] do
    resources :items, only: [:index, :new, :create, :show]
  end
  get '/' => 'sessions#home'
  get '/signup' => 'users#new'
	get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  get '/auth/facebook/callback' =>'sessions#facebook_omni'
  post '/lists/:id' => 'lists#destroy'
  get '/logout' => 'sessions#destroy'
 # post '/list/remove' => 'list#destroy'
  #post '/categories/:id/items/new' => 'items#create'
  #post '/categories/:id/items/new' => 'list_items#create'
  # get '/categories' => 'categories#index'
  # get '/categories/:id/items/:item_id' =>  'items#index'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :lists
    has_many :list_items, through: :lists 
    has_many :items, through: :list_items
    #single source of truth, a deeeeeeep relationship
    has_many :purchased, class_name: "ListItem", foreign_key: :user_id
    #I want the method [purchased] to return an array of list_items where the foreign_key user_id matches this instance
    #has_secure_password if: :facebook_login?
    has_secure_password 

      
    validates :username, :email, presence: true
    validates :username, :email, uniqueness: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    include UsersHelper
    
    def new
        #load the signup form
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        @lists = @user.lists
        
    end

    private
    
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper

  def find_lists(list)
 
    ListItem.find_by(list_id: list.id)
  end
end

app/views/users/new.html.erb
<div class="col-md-12">
	<% if !flash[:success].blank? %>
		<div class="notice">
			<%= flash[:success] %>
		</div>
	<% end %>

	<h1>Sign Up</h1>

	<%= form_for(@user)  do |f| %>
		<%= f.label :username %>
		<%= f.text_field :username %>

		<%= f.label :email  %>
		<%= f.email_field :email %>

		<%=  f.label :password %>
		<%=  f.password_field :password %>

		<%=  f.submit %>
	<% end %>

	<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do |error|%>
		<p><%= error %></p>

		<% end %>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="col-md-12">
    <h1><%= @user.username.capitalize %> Lists</h1>
    <% if !flash[:success].blank? %>
        <div class="alert alert-success">
            <%= flash[:success] %>
        </div>
    <% end %>
    <div class="row list">
        <% if @user.lists.empty? %>
            <h4>You currently do not have any lists</h4>   
        <% else %>
            <ul class="list-group list-group-flush">
                <% @user.lists.each do |list| %> 
                    <li class="list-group-item">
                    <%= link_to list.name.capitalize, user_list_path(@user, list) %> 
                    <% if @user.id == current_user.id %>
                        | <%= link_to "Remove List", list, method: :destroy, data: { confirm: "Are you sure you want to remove this list?" } %>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        <% end %>
    </div>
    
    <div class="row">
        <div class="col-md-6">
        <% if @user.id == current_user.id %>
            <p> <%= link_to "Create a new gift list", new_user_list_path(@user), class: "btn btn-primary btn-block" %></p>
        <% end %>
        </div>
        <div class="col-md-6">
            <%= link_to "See other's gift lists!", lists_path, class: "btn btn-primary btn-block" %>
        </div>
    </div>

    <% if !flash[:destroy].blank? %>
        <div class="alert alert-info">
            <%= flash[:destroy] %>
        </div>
    <% end %>

</div>