config/routes.rb
Rails.application.routes.draw do
  #resources :lists, only: [:new, :create]
  resources :users do
    resources :lists do
      resources :list_items, only: [:new, :edit, :update]
    end
  end
  #resources :items
  resources :list_items, except: [:index, :new]
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:index, :show] do
    resources :items, only: [:index, :new, :create, :show]
  end
  get '/' => 'sessions#home'
  get '/signup' => 'users#new'
	get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  get '/auth/facebook/callback' =>'sessions#facebook_omni'
  post '/lists/:id' => 'lists#destroy'
  get '/logout' => 'sessions#destroy'
 # post '/list/remove' => 'list#destroy'
  #post '/categories/:id/items/new' => 'items#create'
  #post '/categories/:id/items/new' => 'list_items#create'
  # get '/categories' => 'categories#index'
  # get '/categories/:id/items/:item_id' =>  'items#index'
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :category
    has_many :list_items
    has_many :lists, through: :list_items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index
        #/categories/:category_id/items
        #/items
        #/how to handle whether a user wants to see all items /index or nested items /categories/:category_id/index
        @category = Category.find(params[:category_id])
        @item = Item.new
       # @category = Category.find(params[:id])
        #@items = @category.items
    end

    def show
        @list_item = ListItem.new
       @item = Item.find(params[:id])
        @lists = current_user.lists
    end

    def create
        
        @list_item = ListItem.find(params[:id])
    end

  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<div class="col-md-12">
    <h1><%= @category.name %></h1>

    <ul class="list-group">
        <% @category.items.each do |item|%>
            <li class="list-group-item"><%= link_to item.name, category_item_path(@category, item) %></li>
        <% end %>
    </ul>
</div>
    

app/views/items/show.html.erb
<div class="col-md-12">
    <h1><%= @item.name %></h1>
    <div class="row list">
        <% if !flash[:error].blank? %>
            <div class="alert alert-info">
                <%= flash[:error] %>
            </div>
        <% end %>
    <div>
    <div class="row">
        <div class="col-md-12">
            <%= form_for(@list_item) do |f| %>

                <%= f.label :name %>
                <%= f.collection_select :list_id, @lists, :id, :name %> 

                <%= f.hidden_field :item_id, value: @item.id %>
                <%= f.submit "Add Item To List"%>
            <% end %>
        </div>
    </div>
    <%= link_to "Back to your lists", user_path(@user), class: "btn btn-primary" %> | <%= link_to "Back to Categories", categories_path, class: "btn btn-secondary" %>

</div>