config/routes.rb
Rails.application.routes.draw do
  #resources :lists, only: [:new, :create]
  resources :users do
    resources :lists do
      resources :list_items, only: [:new, :edit, :update]
    end
  end
  #resources :items
  resources :list_items, except: [:index, :new]
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:index, :show] do
    resources :items, only: [:index, :new, :create, :show]
  end
  get '/' => 'sessions#home'
  get '/signup' => 'users#new'
	get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  get '/auth/facebook/callback' =>'sessions#facebook_omni'
  post '/lists/:id' => 'lists#destroy'
  get '/logout' => 'sessions#destroy'
 # post '/list/remove' => 'list#destroy'
  #post '/categories/:id/items/new' => 'items#create'
  #post '/categories/:id/items/new' => 'list_items#create'
  # get '/categories' => 'categories#index'
  # get '/categories/:id/items/:item_id' =>  'items#index'
end

app/models/list_item.rb
class ListItem < ApplicationRecord
    belongs_to :item
    belongs_to :list 
    #belongs_to :user, through: :list this doesn't work
    #try this maybe? delegate :user, to: :list
    belongs_to :purchaser, class_name: "User", foreign_key: "user_id", optional: true 
    #I want to refer to the user_id on my column as a purchaser

    validates :list_id, uniqueness: { scope: :item_id, message: "You already have this item in your list." }

    def purchased?
        self.purchaser != nil
    end

    def self.find_list(params_id)
        where(list_id: params_id)
    end

end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
 
    def new
      @list_item = ListItem.new
     @lists = current_user.lists
     
    end

    def create
        @list_item = ListItem.new(list_id: params[:list_item][:list_id], item_id: params[:list_item][:item_id])
        if @list_item.save
           redirect_to user_list_path(current_user, @list_item.list_id)  
        else 
         
            item = Item.find_by(id: params[:list_item][:item_id]) #use to pass in category_item_path
            category = Category.find_by(id: item.category_id) #use to pass in category_item_path
            flash[:error] = @list_item.errors.messages[:list_id][0]
            redirect_to category_item_path(category, item)
        end
    end

    def show
        @list = List.find(params[:id])
    end

    def edit
        @listItem = ListItem.find_by(list_id: params[:id] )
        @listItems = ListItem.where(list_id: params[:id])
    end

    def update
        @listItems = ListItem.find_by(list_id: params[:id], item_id: params[:format] )
        list = List.find(params[:id])
        list_owner = list.user
       # binding.pry
        user = User.find_by(id: current_user.id)
        if params[:item][:checked] == "0"
            @listItems.update(purchaser: nil)
        else
            @listItems.update(purchaser: user)
        end

        redirect_to user_list_path(list_owner.id, list.id)
    end

    def destroy
       # 
        list = ListItem.find_by(id: params[:id]).list.id
        list_item = ListItem.find_by(id: params[:id])
        item_name = Item.find_by(id: list_item.item_id).name
        flash[:destroy] = "#{item_name} is now removed from your list."
        list_item.destroy
        user = current_user.id
        redirect_to user_list_path(user, list)
    end
   

    private


    def list_items_params
        params.require(:list_item).permit(:category_id)
    end
end

app/helpers/list_items_helper.rb
module ListItemsHelper

    def find_listItem(item)
       ListItem.find_by(list_id: params[:id], item_id: item.id)
    end
end

app/views/list_items/show.html.erb
<h1><%= @user.username.capitalize %>'s, <%= @list.name.capitalize %> Gift List</h1>
<ul>
<% binding.pry %>
<!-- ---------------------------------------------Test  --------------------------------------------------------------->
        
    <%= form_for(@listItem) do |list_item|%>
        <% @list.items.each do |item| %>
        <%= f.check_box :checked, :class => "toggle", :checked => ( true if found_listItem(item, @list).purchased? ) %>
    <% end %>
   <!-- <li>
        <div>
            <% if current_user != @user %>
                <%= form_for([@list, item]) do |f| %>
                    <%= f.check_box :checked, :class => "toggle", :checked => ( true if found_listItem(item, @list).purchased? ) %> 
                <% end %>
            <% end %>

            <% if @user.id == current_user.id && found_listItem(item, @list).purchased? %>
                *** Purchased by: <%= User.find(found_listItem(item, @list).user_id).username.capitalize %> *** | 
            <% end %>

            <%= item.name %> 
        
            <% if @user.id == current_user.id %>
            | <%= link_to "Remove Item", find_listItem(item), method: :delete, data: { confirm: "Are you sure you want to remove this item?" } %>
            <% end %>
        </div>
    </li>
        
        <% end %>
</ul>-->
 <% if @user.id == current_user.id %>
    <%= link_to "Add Items To Your List",  categories_path %> | <%= link_to "Go to all lists", user_path(@user) %>
<% else %>
    <%= link_to "Go back to your own gift lists", user_path(current_user) %> | <%= link_to "See other's gift lists!", lists_path %>
<% end %>


 